import { Encounter, Item, Species } from './types';

export const SPECIES: Record<string, Species> = {
  angry_sheep: {
    id: 'angry_sheep',
    name: 'Angry Sheep',
    description: 'A stubborn little bruiser with a cracked brass bell and a dangerous headbutt.',
    baseStats: { str: 7, dex: 10, con: 9, int: 2, wis: 8, cha: 4 },
    growth: { str: 1, dex: 1, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Grass, oats, and unattended laundry',
    image: '🐑',
    cost: 20,
    specialAbility: {
      name: 'Bell Ringer',
      description: 'A rattling headbutt that staggers slower prey.',
      cooldown: 2,
      damageMultiplier: 1.25,
      resource: 'energy',
      cost: 14,
      accuracyBonus: 2,
    },
  },
  pet_rat: {
    id: 'pet_rat',
    name: 'Pet Rat',
    description: 'Quick, clever, and suspiciously good at escaping pockets and locks.',
    baseStats: { str: 6, dex: 14, con: 8, int: 2, wis: 10, cha: 4 },
    growth: { str: 0, dex: 2, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'True Neutral',
    diet: 'Anything edible, preferably stolen',
    image: '🐀',
    cost: 35,
    specialAbility: {
      name: 'Filch and Bite',
      description: 'Darts in with a vicious bite before vanishing into cover.',
      cooldown: 2,
      damageMultiplier: 1.3,
      resource: 'energy',
      cost: 16,
      accuracyBonus: 4,
    },
  },
  gelatinous_cube: {
    id: 'gelatinous_cube',
    name: 'Gelatinous Cube',
    description: 'A transparent ooze that absorbs and digests organic matter. Very clean.',
    baseStats: { str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1 },
    growth: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Anything Organic',
    image: '🧊',
    cost: 50,
    specialAbility: {
      name: 'Engulf',
      description: 'Swallows the target whole.',
      cooldown: 3,
      damageMultiplier: 1.5,
      resource: 'hunger',
      cost: 18,
      accuracyBonus: 2,
    },
  },
  stirge: {
    id: 'stirge',
    name: 'Stirge',
    description: 'A winged bloodsucker with a nasty proboscis and no respect for personal space.',
    baseStats: { str: 8, dex: 15, con: 9, int: 2, wis: 8, cha: 3 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Fresh blood',
    image: '🦟',
    cost: 60,
    specialAbility: {
      name: 'Blood Lance',
      description: 'Drills in and siphons vitality in a single brutal pass.',
      cooldown: 2,
      damageMultiplier: 1.4,
      resource: 'hp',
      cost: 5,
      accuracyBonus: 3,
    },
  },
  blink_dog: {
    id: 'blink_dog',
    name: 'Blink Dog',
    description: 'A fey canine that can teleport short distances. Very loyal.',
    baseStats: { str: 12, dex: 17, con: 12, int: 10, wis: 13, cha: 11 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'Lawful Good',
    diet: 'Meat',
    image: '🐕',
    cost: 100,
    specialAbility: {
      name: 'Teleport Bite',
      description: 'Blinks behind the enemy for a surprise attack.',
      cooldown: 2,
      damageMultiplier: 1.4,
      resource: 'energy',
      cost: 24,
      accuracyBonus: 4,
    },
  },
  skeleton_squire: {
    id: 'skeleton_squire',
    name: 'Skeleton Squire',
    description: 'A rattling undead retainer that still polishes imaginary armor before battle.',
    baseStats: { str: 9, dex: 10, con: 10, int: 6, wis: 6, cha: 4 },
    growth: { str: 2, dex: 0, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Bone dust and necrotic vibes',
    image: '💀',
    cost: 140,
    specialAbility: {
      name: 'Shield Bash',
      description: 'Smashes through guard with a dead-eyed martial charge.',
      cooldown: 3,
      damageMultiplier: 1.6,
      resource: 'energy',
      cost: 18,
      accuracyBonus: 2,
    },
  },
  mimic: {
    id: 'mimic',
    name: 'Mimic',
    description: 'A shape-shifting predator able to take on the form of inanimate objects. Usually a chest.',
    baseStats: { str: 17, dex: 12, con: 15, int: 5, wis: 13, cha: 8 },
    growth: { str: 2, dex: 0, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'True Neutral',
    diet: 'Adventurers',
    image: '🧰',
    cost: 150,
    specialAbility: {
      name: 'Adhesive Strike',
      description: 'Traps the enemy with sticky pseudopods.',
      cooldown: 3,
      damageMultiplier: 1.8,
      resource: 'hp',
      cost: 8,
      accuracyBonus: 2,
    },
  },
  owlbear: {
    id: 'owlbear',
    name: 'Owlbear',
    description: 'A monstrous cross between a giant owl and a bear. Aggressive and huggable.',
    baseStats: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    growth: { str: 2, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Raw Meat',
    image: '🦉',
    cost: 200,
    specialAbility: {
      name: 'Bear Hug',
      description: 'A crushing embrace that shatters armor.',
      cooldown: 3,
      damageMultiplier: 2.0,
      resource: 'energy',
      cost: 28,
      accuracyBonus: 1,
    },
  },
  imp: {
    id: 'imp',
    name: 'Imp',
    description: 'A needling little fiend that starts fragile but grows terrifyingly cunning.',
    baseStats: { str: 7, dex: 14, con: 8, int: 12, wis: 11, cha: 12 },
    growth: { str: 1, dex: 2, con: 1, int: 1, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Sulfur, gossip, and soul crumbs',
    image: '😈',
    cost: 260,
    specialAbility: {
      name: 'Hellsting',
      description: 'A venomous infernal strike delivered with spiteful glee.',
      cooldown: 3,
      damageMultiplier: 1.7,
      resource: 'energy',
      cost: 18,
      accuracyBonus: 4,
    },
  },
  displacer_beast: {
    id: 'displacer_beast',
    name: 'Displacer Beast',
    description: 'A feline menace with six legs and two tentacle whips. Hates blink dogs.',
    baseStats: { str: 18, dex: 15, con: 16, int: 6, wis: 12, cha: 8 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Fresh Prey',
    image: '🐆',
    cost: 300,
    specialAbility: {
      name: 'Tentacle Whip',
      description: 'Lashes out with spiked tentacles.',
      cooldown: 2,
      damageMultiplier: 1.5,
      resource: 'energy',
      cost: 18,
      accuracyBonus: 3,
    },
  },
  rust_monster: {
    id: 'rust_monster',
    name: 'Rust Monster',
    description: 'An insectoid creature that feeds on metal. Keep away from your coins.',
    baseStats: { str: 13, dex: 12, con: 13, int: 2, wis: 13, cha: 6 },
    growth: { str: 1, dex: 1, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Metals',
    image: '🪲',
    cost: 400,
    specialAbility: {
      name: 'Antennae Touch',
      description: 'Corrodes the enemy\'s weapons and armor.',
      cooldown: 3,
      damageMultiplier: 1.6,
      resource: 'hunger',
      cost: 14,
      accuracyBonus: 2,
    },
  },
  hell_hound_pup: {
    id: 'hell_hound_pup',
    name: 'Hell Hound Pup',
    description: 'Still small enough to fit by the hearth, still hot enough to char the rugs.',
    baseStats: { str: 10, dex: 12, con: 11, int: 4, wis: 8, cha: 6 },
    growth: { str: 2, dex: 1, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Charred bones and cinders',
    image: '🔥',
    cost: 550,
    specialAbility: {
      name: 'Cinder Burst',
      description: 'Belches a cone of smoke and embers that scales hard with age.',
      cooldown: 3,
      damageMultiplier: 1.9,
      resource: 'hunger',
      cost: 18,
      accuracyBonus: 3,
    },
  },
  mind_flayer: {
    id: 'mind_flayer',
    name: 'Mind Flayer',
    description: 'A psionic tyrant from the Underdark. Loves a good brain.',
    baseStats: { str: 11, dex: 12, con: 12, int: 19, wis: 17, cha: 17 },
    growth: { str: 0, dex: 0, con: 1, int: 2, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Brains',
    image: '🦑',
    cost: 800,
    specialAbility: {
      name: 'Mind Blast',
      description: 'Emits psychic energy to crush the enemy\'s will.',
      cooldown: 4,
      damageMultiplier: 2.2,
      resource: 'hp',
      cost: 10,
      accuracyBonus: 5,
    },
  },
  black_dragon_wyrmling: {
    id: 'black_dragon_wyrmling',
    name: 'Black Dragon Wyrmling',
    description: 'Mean, clever, and still undersized. It starts lean and becomes monstrous with age.',
    baseStats: { str: 12, dex: 11, con: 11, int: 10, wis: 9, cha: 10 },
    growth: { str: 2, dex: 1, con: 2, int: 1, wis: 1, cha: 1 },
    alignment: 'Chaotic Evil',
    diet: 'Carrion, swamp eels, and shiny trophies',
    image: '🐲',
    cost: 1200,
    specialAbility: {
      name: 'Acid Breath',
      description: 'Unleashes a corrosive torrent that gets nastier each level band.',
      cooldown: 4,
      damageMultiplier: 2.4,
      resource: 'hunger',
      cost: 20,
      accuracyBonus: 3,
    },
  },
  red_dragon_wyrmling: {
    id: 'red_dragon_wyrmling',
    name: 'Red Dragon Wyrmling',
    description: 'A young, arrogant, and fiery dragon. Thinks it owns your parlour.',
    baseStats: { str: 19, dex: 10, con: 17, int: 12, wis: 11, cha: 15 },
    growth: { str: 2, dex: 1, con: 2, int: 1, wis: 0, cha: 1 },
    alignment: 'Chaotic Evil',
    diet: 'Cooked Meat & Gold',
    image: '🐉',
    cost: 1500,
    specialAbility: {
      name: 'Fire Breath',
      description: 'Exhales a cone of destructive fire.',
      cooldown: 4,
      damageMultiplier: 2.5,
      resource: 'hunger',
      cost: 22,
      accuracyBonus: 3,
    },
  },
  beholder: {
    id: 'beholder',
    name: 'Beholder',
    description: 'A floating orb of flesh with a large mouth, single central eye, and many smaller eyestalks.',
    baseStats: { str: 10, dex: 14, con: 18, int: 17, wis: 15, cha: 17 },
    growth: { str: 1, dex: 1, con: 2, int: 2, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Anything it wants',
    image: '👁️',
    cost: 3000,
    specialAbility: {
      name: 'Death Ray',
      description: 'Fires a necrotic beam from an eyestalk.',
      cooldown: 5,
      damageMultiplier: 3.0,
      resource: 'hp',
      cost: 12,
      accuracyBonus: 4,
    },
  },
  dracolich_hatchling: {
    id: 'dracolich_hatchling',
    name: 'Dracolich Hatchling',
    description: 'A brittle, expensive horror that begins underfed and skeletal, then scales into a ruinous legend.',
    baseStats: { str: 10, dex: 9, con: 10, int: 11, wis: 10, cha: 12 },
    growth: { str: 2, dex: 1, con: 2, int: 2, wis: 1, cha: 2 },
    alignment: 'Chaotic Evil',
    diet: 'Bone marrow, grave fog, and curses',
    image: '☠️',
    cost: 2600,
    specialAbility: {
      name: 'Graveflame',
      description: 'Breathes necrotic fire that leaves the air itself haunted.',
      cooldown: 5,
      damageMultiplier: 3.1,
      resource: 'hp',
      cost: 14,
      accuracyBonus: 4,
    },
  },
  tarrasque: {
    id: 'tarrasque',
    name: 'Tarrasque',
    description: 'The legendary engine of destruction. How did you even catch this?',
    baseStats: { str: 30, dex: 11, con: 30, int: 3, wis: 11, cha: 11 },
    growth: { str: 2, dex: 0, con: 3, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Everything',
    image: '🦖',
    cost: 10000,
    specialAbility: {
      name: 'Swallow Whole',
      description: 'Devours the enemy in a single bite.',
      cooldown: 6,
      damageMultiplier: 4.0,
      resource: 'hp',
      cost: 18,
      accuracyBonus: 2,
    },
  },
};

export const HEROES: Encounter[] = [
  {
    id: 'mosquito',
    name: 'Mosquito',
    description: 'A tiny but relentless bloodsucker that somehow insists on heroically ruining your evening.',
    level: 1,
    hp: 8,
    maxHp: 8,
    stats: { str: 6, dex: 14, con: 8, int: 1, wis: 7, cha: 1 },
    reward: 8,
    icon: '🦟',
    tier: 'trivial',
  },
  {
    id: 'pet_rat',
    name: 'Pet Rat',
    description: 'A rescued street rat defending its corner with admirable nerve and unpleasant teeth.',
    level: 2,
    hp: 12,
    maxHp: 12,
    stats: { str: 8, dex: 13, con: 9, int: 2, wis: 10, cha: 4 },
    reward: 12,
    icon: '🐀',
    tier: 'trivial',
  },
  {
    id: 'angry_sheep',
    name: 'Angry Sheep',
    description: 'A fiercely territorial farm guardian with a bell, a glare, and a civic sense of duty.',
    level: 3,
    hp: 18,
    maxHp: 18,
    stats: { str: 10, dex: 10, con: 10, int: 2, wis: 8, cha: 3 },
    reward: 18,
    icon: '🐑',
    tier: 'low',
  },
  {
    id: 'town_guard',
    name: 'Town Guard',
    description: 'A disciplined watchman armed with a spear, a shield, and inconveniently decent morals.',
    level: 4,
    hp: 28,
    maxHp: 28,
    stats: { str: 12, dex: 11, con: 12, int: 9, wis: 10, cha: 9 },
    reward: 28,
    icon: '🛡️',
    tier: 'low',
  },
  {
    id: 'lantern_acolyte',
    name: 'Lantern Acolyte',
    description: 'A temple novice carrying a mace, bright conviction, and enough healing prayers to be annoying.',
    level: 5,
    hp: 36,
    maxHp: 36,
    stats: { str: 11, dex: 10, con: 12, int: 11, wis: 14, cha: 12 },
    reward: 42,
    icon: '🕯️',
    tier: 'standard',
  },
  {
    id: 'ranger_scout',
    name: 'Ranger Scout',
    description: 'A sharp-eyed wilderness tracker who insists your creatures are an ecological concern.',
    level: 6,
    hp: 44,
    maxHp: 44,
    stats: { str: 13, dex: 15, con: 12, int: 11, wis: 13, cha: 10 },
    reward: 56,
    icon: '🏹',
    tier: 'standard',
  },
  {
    id: 'squire_captain',
    name: 'Squire Captain',
    description: 'A young commander with good posture, polished mail, and more courage than experience.',
    level: 7,
    hp: 54,
    maxHp: 54,
    stats: { str: 15, dex: 12, con: 14, int: 11, wis: 11, cha: 12 },
    reward: 72,
    icon: '⚔️',
    tier: 'standard',
  },
  {
    id: 'apprentice_mage',
    name: 'Apprentice Mage',
    description: 'A bookish prodigy eager to prove that a well-cast spell can solve any monster problem.',
    level: 8,
    hp: 58,
    maxHp: 58,
    stats: { str: 9, dex: 12, con: 12, int: 16, wis: 13, cha: 12 },
    reward: 92,
    icon: '📘',
    tier: 'standard',
  },
  {
    id: 'temple_hound',
    name: 'Temple Hound',
    description: 'A holy war dog bred to sniff out fiends, thieves, and parlours with suspicious basements.',
    level: 9,
    hp: 70,
    maxHp: 70,
    stats: { str: 16, dex: 14, con: 14, int: 4, wis: 13, cha: 8 },
    reward: 114,
    icon: '🐕',
    tier: 'standard',
  },
  {
    id: 'griffon_rider',
    name: 'Griffon Rider',
    description: 'An aerial lancer from the city watch, all feathers, brass, and lawful momentum.',
    level: 10,
    hp: 82,
    maxHp: 82,
    stats: { str: 17, dex: 15, con: 15, int: 12, wis: 12, cha: 13 },
    reward: 140,
    icon: '🦅',
    tier: 'elite',
  },
  {
    id: 'druid_warden',
    name: 'Druid Warden',
    description: 'A forest guardian who has decided your enterprise counts as unnatural interference.',
    level: 11,
    hp: 96,
    maxHp: 96,
    stats: { str: 14, dex: 13, con: 16, int: 13, wis: 17, cha: 12 },
    reward: 170,
    icon: '🌿',
    tier: 'elite',
  },
  {
    id: 'paladin_errant',
    name: 'Paladin Errant',
    description: 'A mounted oathsworn crusader with radiant steel and an absolutely exhausting code.',
    level: 12,
    hp: 112,
    maxHp: 112,
    stats: { str: 18, dex: 12, con: 17, int: 12, wis: 14, cha: 16 },
    reward: 204,
    icon: '✨',
    tier: 'elite',
  },
  {
    id: 'pegasus_knight',
    name: 'Pegasus Knight',
    description: 'A skyborne champion sweeping in from the upper winds to put down airborne nuisances.',
    level: 13,
    hp: 128,
    maxHp: 128,
    stats: { str: 18, dex: 16, con: 17, int: 12, wis: 14, cha: 15 },
    reward: 242,
    icon: '🐎',
    tier: 'elite',
  },
  {
    id: 'unicorn_guardian',
    name: 'Unicorn Guardian',
    description: 'A radiant woodland sentinel whose mercy unfortunately does not extend to your battle roster.',
    level: 14,
    hp: 146,
    maxHp: 146,
    stats: { str: 19, dex: 16, con: 18, int: 11, wis: 17, cha: 18 },
    reward: 284,
    icon: '🦄',
    tier: 'elite',
  },
  {
    id: 'veteran_cleric',
    name: 'Veteran Cleric',
    description: 'A battle-priest with calm eyes, heavy armor, and enough divine power to make this personal.',
    level: 15,
    hp: 166,
    maxHp: 166,
    stats: { str: 17, dex: 11, con: 18, int: 13, wis: 18, cha: 16 },
    reward: 330,
    icon: '⛪',
    tier: 'elite',
  },
  {
    id: 'storm_sorcerer',
    name: 'Storm Sorcerer',
    description: 'A smiling duelist wrapped in wind and lightning, treating the arena like a weather experiment.',
    level: 16,
    hp: 188,
    maxHp: 188,
    stats: { str: 12, dex: 16, con: 17, int: 15, wis: 14, cha: 19 },
    reward: 380,
    icon: '⛈️',
    tier: 'elite',
  },
  {
    id: 'deva_emissary',
    name: 'Deva Emissary',
    description: 'A celestial envoy sent to restore order, light, and a deeply inconvenient amount of judgment.',
    level: 17,
    hp: 212,
    maxHp: 212,
    stats: { str: 20, dex: 17, con: 18, int: 17, wis: 18, cha: 19 },
    reward: 436,
    icon: '😇',
    tier: 'boss',
  },
  {
    id: 'archdruid',
    name: 'Archdruid',
    description: 'An elder shapechanger who regards your stable of monstrosities as a policy failure.',
    level: 18,
    hp: 238,
    maxHp: 238,
    stats: { str: 15, dex: 14, con: 19, int: 16, wis: 20, cha: 17 },
    reward: 496,
    icon: '🍃',
    tier: 'boss',
  },
  {
    id: 'planetar_guardian',
    name: 'Planetar Guardian',
    description: 'A towering heavenly enforcer descending with sword drawn and zero tolerance for evil pets.',
    level: 19,
    hp: 266,
    maxHp: 266,
    stats: { str: 23, dex: 18, con: 20, int: 18, wis: 19, cha: 20 },
    reward: 562,
    icon: '🪽',
    tier: 'boss',
  },
  {
    id: 'gold_dragon_ally',
    name: 'Gold Dragon Ally',
    description: 'A noble dragon who would prefer diplomacy but has reluctantly agreed that force is faster.',
    level: 20,
    hp: 296,
    maxHp: 296,
    stats: { str: 24, dex: 16, con: 22, int: 18, wis: 19, cha: 21 },
    reward: 634,
    icon: '🐲',
    tier: 'boss',
  },
  {
    id: 'eladrin_blademaster',
    name: 'Eladrin Blademaster',
    description: 'A fey sword-saint flickering between seasons and striking before thought catches up.',
    level: 21,
    hp: 328,
    maxHp: 328,
    stats: { str: 22, dex: 21, con: 21, int: 18, wis: 17, cha: 20 },
    reward: 712,
    icon: '🌟',
    tier: 'boss',
  },
  {
    id: 'solar_champion',
    name: 'Solar Champion',
    description: 'An angelic warlord blazing with enough sanctified force to sterilize the entire arena.',
    level: 22,
    hp: 362,
    maxHp: 362,
    stats: { str: 26, dex: 20, con: 22, int: 20, wis: 20, cha: 22 },
    reward: 798,
    icon: '☀️',
    tier: 'boss',
  },
  {
    id: 'ancient_treant',
    name: 'Ancient Treant',
    description: 'A walking cathedral of bark and patience, awakened to end what it calls your indoor blight.',
    level: 23,
    hp: 398,
    maxHp: 398,
    stats: { str: 27, dex: 10, con: 25, int: 16, wis: 20, cha: 18 },
    reward: 892,
    icon: '🌳',
    tier: 'boss',
  },
  {
    id: 'kirin_herald',
    name: 'Ki-rin Herald',
    description: 'A heavenly beast bringing omens, thunder, and a complete lack of respect for evil dragons.',
    level: 24,
    hp: 436,
    maxHp: 436,
    stats: { str: 25, dex: 18, con: 24, int: 20, wis: 22, cha: 23 },
    reward: 994,
    icon: '🦌',
    tier: 'boss',
  },
  {
    id: 'bahamuts_chosen',
    name: "Bahamut's Chosen",
    description: 'A legendary draconic champion in radiant armor, carrying the final word on monster management.',
    level: 25,
    hp: 476,
    maxHp: 476,
    stats: { str: 28, dex: 19, con: 25, int: 19, wis: 22, cha: 24 },
    reward: 1104,
    icon: '👑',
    tier: 'boss',
  },
  {
    id: 'tiamat',
    name: 'Tiamat the Dragon Queen',
    description: 'Five-headed catastrophe, tyrant of dragons, and the only opponent here who is evil on purpose.',
    level: 26,
    hp: 540,
    maxHp: 540,
    stats: { str: 30, dex: 18, con: 28, int: 22, wis: 21, cha: 26 },
    reward: 1400,
    icon: '🐉',
    tier: 'boss',
  },
];

export const ENCOUNTERS = HEROES;

export const ITEMS: Record<string, Item> = {
  monster_chow: {
    id: 'monster_chow',
    name: 'Monster Chow',
    description: 'Restores 30 Hunger.',
    cost: 10,
    type: 'food',
    value: 30,
    icon: '🍖',
  },
  minor_potion: {
    id: 'minor_potion',
    name: 'Minor Potion of Healing',
    description: 'Restores 20 HP.',
    cost: 20,
    type: 'heal',
    value: 20,
    icon: '🧪',
  },
  major_potion: {
    id: 'major_potion',
    name: 'Major Potion of Healing',
    description: 'Restores 50 HP.',
    cost: 50,
    type: 'heal',
    value: 50,
    icon: '⚗️',
  },
  pet_brush: {
    id: 'pet_brush',
    name: 'Enchanted Brush',
    description: 'Restores 20 Happiness.',
    cost: 15,
    type: 'social',
    value: 20,
    icon: '🪮',
  },
  haste_potion: {
    id: 'haste_potion',
    name: 'Potion of Haste',
    description: 'Battle: Your pet attacks twice for the next 3 turns.',
    cost: 40,
    type: 'buff',
    value: 3,
    icon: '⚡',
  },
};
