import type { Encounter, EncounterAbility, Item, Species, SpecialAbility } from './types';

function petAbility(
  name: string,
  description: string,
  cooldown: number,
  damageMultiplier: number,
  resource: SpecialAbility['resource'],
  cost: number,
  accuracyBonus: number,
): SpecialAbility {
  return { name, description, cooldown, damageMultiplier, resource, cost, accuracyBonus };
}

function heroAbility(
  name: string,
  description: string,
  cooldown: number,
  damageMultiplier: number,
  accuracyBonus: number,
): EncounterAbility {
  return { name, description, cooldown, damageMultiplier, accuracyBonus };
}

const speciesList: Species[] = [
  {
    id: 'angry_sheep',
    name: 'Angry Sheep',
    description: 'A stubborn little bruiser with a cracked brass bell and a dangerous headbutt. It treats every doorway like a battlefield.',
    baseStats: { str: 7, dex: 10, con: 9, int: 2, wis: 8, cha: 4 },
    growth: { str: 1, dex: 1, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Grass, oats, and unattended laundry',
    image: '🐑',
    cost: 25,
    specialAbility: petAbility('Bell Ringer', 'A rattling headbutt that staggers slower prey.', 2, 1.25, 'energy', 14, 2),
  },
  {
    id: 'pet_rat',
    name: 'Pet Rat',
    description: 'Quick, clever, and suspiciously good at escaping pockets and locks. It can vanish into clutter and return with treasure.',
    baseStats: { str: 6, dex: 14, con: 8, int: 2, wis: 10, cha: 4 },
    growth: { str: 0, dex: 2, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'True Neutral',
    diet: 'Anything edible, preferably stolen',
    image: '🐀',
    cost: 45,
    specialAbility: petAbility('Filch and Bite', 'Darts in with a vicious bite before vanishing into cover.', 2, 1.3, 'energy', 16, 4),
  },
  {
    id: 'gelatinous_cube',
    name: 'Gelatinous Cube',
    description: 'A transparent ooze that absorbs and digests organic matter. The floors have never looked better.',
    baseStats: { str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1 },
    growth: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Anything organic',
    image: '🧊',
    cost: 70,
    specialAbility: petAbility('Engulf', 'Swallows the target whole.', 3, 1.5, 'hunger', 18, 2),
  },
  {
    id: 'stirge',
    name: 'Stirge',
    description: 'A winged bloodsucker with a nasty proboscis and no respect for personal space. It vibrates with malicious hunger.',
    baseStats: { str: 8, dex: 15, con: 9, int: 2, wis: 8, cha: 3 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Fresh blood',
    image: '🦟',
    cost: 110,
    specialAbility: petAbility('Blood Lance', 'Drills in and siphons vitality in a single brutal pass.', 2, 1.4, 'hp', 5, 3),
  },
  {
    id: 'blink_dog',
    name: 'Blink Dog',
    description: 'A fey canine that can teleport short distances. It paces in and out of reality when excited.',
    baseStats: { str: 12, dex: 17, con: 12, int: 10, wis: 13, cha: 11 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'Lawful Good',
    diet: 'Meat',
    image: '🐕',
    cost: 180,
    specialAbility: petAbility('Teleport Bite', 'Blinks behind the enemy for a surprise attack.', 2, 1.4, 'energy', 24, 4),
  },
  {
    id: 'skeleton_squire',
    name: 'Skeleton Squire',
    description: 'A rattling undead retainer that still polishes imaginary armor before battle. It still salutes before charging.',
    baseStats: { str: 9, dex: 10, con: 10, int: 6, wis: 6, cha: 4 },
    growth: { str: 2, dex: 0, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Bone dust and necrotic vibes',
    image: '💀',
    cost: 280,
    specialAbility: petAbility('Shield Bash', 'Smashes through guard with a dead-eyed martial charge.', 3, 1.6, 'energy', 18, 2),
  },
  {
    id: 'mimic',
    name: 'Mimic',
    description: 'A shape-shifting predator able to take on the form of inanimate objects. It absolutely expects you to touch it first.',
    baseStats: { str: 17, dex: 12, con: 15, int: 5, wis: 13, cha: 8 },
    growth: { str: 2, dex: 0, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'True Neutral',
    diet: 'Adventurers',
    image: '🧰',
    cost: 300,
    specialAbility: petAbility('Adhesive Strike', 'Traps the enemy with sticky pseudopods.', 3, 1.8, 'hp', 8, 2),
  },
  {
    id: 'goblin',
    name: 'Goblin',
    description: 'A knife-happy tunnel raider with quick hands, quicker feet, and an alarming amount of confidence. It narrates its own ambushes under its breath.',
    baseStats: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    growth: { str: 1, dex: 1, con: 1, int: 1, wis: 0, cha: 0 },
    alignment: 'Neutral Evil',
    diet: 'Stolen pies, cave lizards, and whatever was in your pack',
    image: '🗡️',
    cost: 320,
    specialAbility: petAbility('Dirty Shiv', 'A mean little stab aimed where armor gaps live.', 2, 1.35, 'energy', 14, 4),
  },
  {
    id: 'zombie',
    name: 'Zombie',
    description: 'A slow, stubborn corpse that keeps moving through sheer necrotic insistence. It wins arguments by outlasting them.',
    baseStats: { str: 13, dex: 6, con: 14, int: 3, wis: 6, cha: 3 },
    growth: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Neutral Evil',
    diet: 'Brains, grave mold, and old marrow',
    image: '🧟',
    cost: 360,
    specialAbility: petAbility('Grave Lurch', 'Staggers forward with a crushing dead-weight slam.', 2, 1.45, 'hunger', 12, 1),
  },
  {
    id: 'owlbear',
    name: 'Owlbear',
    description: 'A monstrous cross between a giant owl and a bear. It sheds feathers everywhere.',
    baseStats: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    growth: { str: 2, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Raw meat',
    image: '🦉',
    cost: 575,
    specialAbility: petAbility('Bear Hug', 'A crushing embrace that shatters armor.', 3, 2.0, 'energy', 28, 1),
  },
  {
    id: 'ochre_jelly',
    name: 'Ochre Jelly',
    description: 'A mustard-colored ooze that slops through halls leaving acid and panic behind it. Locks and hinges dissolve around it.',
    baseStats: { str: 15, dex: 6, con: 16, int: 2, wis: 6, cha: 1 },
    growth: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Carrion, mold, and dungeon runoff',
    image: '🟡',
    cost: 640,
    specialAbility: petAbility('Acid Lash', 'Flings a burning pseudopod that keeps eating through the target.', 3, 1.55, 'hunger', 16, 2),
  },
  {
    id: 'harpy',
    name: 'Harpy',
    description: 'A cliff-haunting singer with talons, vanity, and a voice that ruins judgment. It knows exactly when the room is listening.',
    baseStats: { str: 12, dex: 14, con: 11, int: 7, wis: 10, cha: 14 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 0, cha: 1 },
    alignment: 'Chaotic Evil',
    diet: 'Fresh meat, stolen wine, and attention',
    image: '🪶',
    cost: 720,
    specialAbility: petAbility('Siren Screech', 'A shrill note that lands just before the talons do.', 3, 1.5, 'energy', 18, 4),
  },
  {
    id: 'imp',
    name: 'Imp',
    description: 'A needling little fiend that starts fragile but grows terrifyingly cunning. It smiles whenever something catches fire.',
    baseStats: { str: 7, dex: 14, con: 8, int: 12, wis: 11, cha: 12 },
    growth: { str: 1, dex: 2, con: 1, int: 1, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Sulfur, gossip, and soul crumbs',
    image: '😈',
    cost: 775,
    specialAbility: petAbility('Hellsting', 'A venomous infernal strike delivered with spiteful glee.', 3, 1.7, 'energy', 18, 4),
  },
  {
    id: 'displacer_beast',
    name: 'Displacer Beast',
    description: 'A feline menace with six legs and two tentacle whips. Looking directly at it never quite helps.',
    baseStats: { str: 18, dex: 15, con: 16, int: 6, wis: 12, cha: 8 },
    growth: { str: 1, dex: 2, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Fresh prey',
    image: '🐆',
    cost: 975,
    specialAbility: petAbility('Tentacle Whip', 'Lashes out with spiked tentacles.', 2, 1.5, 'energy', 18, 3),
  },
  {
    id: 'black_pudding',
    name: 'Black Pudding',
    description: 'A glossy tide of annihilation that dissolves armor, stonework, and optimism. Even the bucket regrets volunteering.',
    baseStats: { str: 18, dex: 5, con: 20, int: 1, wis: 6, cha: 1 },
    growth: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Metal, flesh, leather, and your floorboards',
    image: '⚫',
    cost: 1180,
    specialAbility: petAbility('Dissolving Surge', 'A tidal slam of corrosive sludge.', 3, 1.75, 'hunger', 20, 2),
  },
  {
    id: 'rust_monster',
    name: 'Rust Monster',
    description: 'An insectoid creature that feeds on metal. It can smell a sword from three rooms away.',
    baseStats: { str: 13, dex: 12, con: 13, int: 2, wis: 13, cha: 6 },
    growth: { str: 1, dex: 1, con: 1, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Metals',
    image: '🪲',
    cost: 1300,
    specialAbility: petAbility('Antennae Touch', "Corrodes the enemy's weapons and armor.", 3, 1.6, 'hunger', 14, 2),
  },
  {
    id: 'hippogriff',
    name: 'Hippogriff',
    description: 'A proud eagle-horse sky hunter that prefers high places, clean dives, and dramatic entrances. It expects admiration after every landing.',
    baseStats: { str: 17, dex: 15, con: 15, int: 4, wis: 12, cha: 8 },
    growth: { str: 2, dex: 1, con: 1, int: 0, wis: 1, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Goat, fish, and cliffside game',
    image: '🪽',
    cost: 1350,
    specialAbility: petAbility('Talon Dive', 'Folds its wings and plunges straight through the target.', 3, 1.7, 'energy', 22, 3),
  },
  {
    id: 'hell_hound_pup',
    name: 'Hell Hound Pup',
    description: 'Still small enough to fit by the hearth, still hot enough to char the rugs. It naps like a coal bed.',
    baseStats: { str: 10, dex: 12, con: 11, int: 4, wis: 8, cha: 6 },
    growth: { str: 2, dex: 1, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Lawful Evil',
    diet: 'Charred bones and cinders',
    image: '🔥',
    cost: 1700,
    specialAbility: petAbility('Cinder Burst', 'Belches a cone of smoke and embers that scales hard with age.', 3, 1.9, 'hunger', 18, 3),
  },
  {
    id: 'troll',
    name: 'Troll',
    description: 'A wiry horror of ropey muscle and spiteful regeneration that gets uglier the longer the fight goes. Lost fingers rarely stay lost for long.',
    baseStats: { str: 18, dex: 13, con: 19, int: 7, wis: 9, cha: 7 },
    growth: { str: 2, dex: 1, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Chaotic Evil',
    diet: 'Anything warm and recently screaming',
    image: '🧌',
    cost: 1850,
    specialAbility: petAbility('Rending Regrowth', 'Tears into the target while burning its own flesh for momentum.', 3, 1.85, 'hp', 10, 2),
  },
  {
    id: 'mind_flayer',
    name: 'Mind Flayer',
    description: 'A psionic tyrant from the Underdark. It watches people like menus.',
    baseStats: { str: 11, dex: 12, con: 12, int: 19, wis: 17, cha: 17 },
    growth: { str: 0, dex: 0, con: 1, int: 2, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Brains',
    image: '🦑',
    cost: 2400,
    specialAbility: petAbility('Mind Blast', "Emits psychic energy to crush the enemy's will.", 4, 2.2, 'hp', 10, 5),
  },
  {
    id: 'wyvern',
    name: 'Wyvern',
    description: 'A venomous lesser dragon built around altitude, malice, and one catastrophically unfair tail. It circles the rafters whenever it gets impatient.',
    baseStats: { str: 19, dex: 14, con: 17, int: 5, wis: 12, cha: 9 },
    growth: { str: 2, dex: 1, con: 2, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Mountain goats, carrion, and armored climbers',
    image: '🐉',
    cost: 2750,
    specialAbility: petAbility('Venom Stinger', 'A diving stab that leaves venom pumping after the impact.', 3, 2.0, 'hp', 9, 3),
  },
  {
    id: 'naga',
    name: 'Naga',
    description: 'A regal serpent sorcerer coiling around ancient secrets and very personal grudges. It speaks like every sentence is a prophecy.',
    baseStats: { str: 16, dex: 15, con: 16, int: 14, wis: 15, cha: 16 },
    growth: { str: 1, dex: 1, con: 2, int: 1, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Sacred fish, incense, and temple offerings',
    image: '🐍',
    cost: 3200,
    specialAbility: petAbility('Hypnotic Coil', 'Locks eyes, coils tight, and crushes the will out of the target.', 4, 1.95, 'energy', 22, 5),
  },
  {
    id: 'black_dragon_wyrmling',
    name: 'Black Dragon Wyrmling',
    description: 'Mean, clever, and still undersized. It sulks magnificently when denied shiny things.',
    baseStats: { str: 12, dex: 11, con: 11, int: 10, wis: 9, cha: 10 },
    growth: { str: 2, dex: 1, con: 2, int: 1, wis: 1, cha: 1 },
    alignment: 'Chaotic Evil',
    diet: 'Carrion, swamp eels, and shiny trophies',
    image: '🐲',
    cost: 3600,
    specialAbility: petAbility('Acid Breath', 'Unleashes a corrosive torrent that gets nastier each level band.', 4, 2.4, 'hunger', 20, 3),
  },
  {
    id: 'necromancer',
    name: 'Necromancer',
    description: 'A grave scholar with patient hands, bad ethics, and a wardrobe that smells faintly embalmed. It labels bones by provenance.',
    baseStats: { str: 9, dex: 12, con: 14, int: 18, wis: 15, cha: 14 },
    growth: { str: 0, dex: 0, con: 1, int: 2, wis: 1, cha: 1 },
    alignment: 'Neutral Evil',
    diet: 'Black tea, grave dust, and stolen relics',
    image: '🕯️',
    cost: 4300,
    specialAbility: petAbility('Soul Hex', 'Brands the target with a curse that lands like a funeral bell.', 4, 2.2, 'hp', 12, 4),
  },
  {
    id: 'red_dragon_wyrmling',
    name: 'Red Dragon Wyrmling',
    description: 'A young, arrogant, and fiery dragon. It keeps trying to annex the sofa.',
    baseStats: { str: 19, dex: 10, con: 17, int: 12, wis: 11, cha: 15 },
    growth: { str: 2, dex: 1, con: 2, int: 1, wis: 0, cha: 1 },
    alignment: 'Chaotic Evil',
    diet: 'Cooked meat and gold',
    image: '🐉',
    cost: 4500,
    specialAbility: petAbility('Fire Breath', 'Exhales a cone of destructive fire.', 4, 2.5, 'hunger', 22, 3),
  },
  {
    id: 'frost_giant',
    name: 'Frost Giant',
    description: 'A glacier-born reaver carrying a chunk of winter on its shoulders and a grudge in both hands. It leaves hoarfrost on the floorboards.',
    baseStats: { str: 23, dex: 9, con: 21, int: 9, wis: 12, cha: 10 },
    growth: { str: 2, dex: 0, con: 2, int: 0, wis: 1, cha: 0 },
    alignment: 'Neutral Evil',
    diet: 'Whale blubber, mammoth, and icy ale',
    image: '🧊',
    cost: 5600,
    specialAbility: petAbility('Avalanche Cleaver', 'Brings down a slab-like weapon with glacial force.', 4, 2.4, 'energy', 28, 2),
  },
  {
    id: 'dracolich_hatchling',
    name: 'Dracolich Hatchling',
    description: 'A brittle, expensive horror that begins underfed and skeletal, then scales into a ruinous legend. Every level makes it look less hypothetical.',
    baseStats: { str: 10, dex: 9, con: 10, int: 11, wis: 10, cha: 12 },
    growth: { str: 2, dex: 1, con: 2, int: 2, wis: 1, cha: 2 },
    alignment: 'Chaotic Evil',
    diet: 'Bone marrow, grave fog, and curses',
    image: '☠️',
    cost: 6500,
    specialAbility: petAbility('Graveflame', 'Breathes necrotic fire that leaves the air itself haunted.', 5, 3.1, 'hp', 14, 4),
  },
  {
    id: 'mummy_lord',
    name: 'Mummy Lord',
    description: 'A wrapped tyrant of dust and curses, still ruling a dead empire from inside a perfectly preserved grudge. It disapproves of modern architecture.',
    baseStats: { str: 18, dex: 10, con: 20, int: 17, wis: 18, cha: 18 },
    growth: { str: 1, dex: 0, con: 2, int: 2, wis: 1, cha: 2 },
    alignment: 'Lawful Evil',
    diet: 'Incense, sacred oils, and temple offerings gone wrong',
    image: '🪬',
    cost: 7600,
    specialAbility: petAbility("Pharaoh's Curse", 'Unleashes a regal malediction that lands like a sandstorm.', 5, 2.5, 'hp', 12, 4),
  },
  {
    id: 'beholder',
    name: 'Beholder',
    description: 'A floating orb of flesh with a large mouth, single central eye, and many smaller eyestalks. Every eyestalk seems to judge a different mistake.',
    baseStats: { str: 10, dex: 14, con: 18, int: 17, wis: 15, cha: 17 },
    growth: { str: 1, dex: 1, con: 2, int: 2, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Anything it wants',
    image: '👁️',
    cost: 8000,
    specialAbility: petAbility('Death Ray', 'Fires a necrotic beam from an eyestalk.', 5, 3.0, 'hp', 12, 4),
  },
  {
    id: 'death_knight',
    name: 'Death Knight',
    description: 'A fallen champion in cursed plate, all black flame, discipline, and unfinished vengeance. It stands so still that the room gets colder.',
    baseStats: { str: 24, dex: 12, con: 22, int: 16, wis: 16, cha: 18 },
    growth: { str: 2, dex: 1, con: 2, int: 1, wis: 1, cha: 1 },
    alignment: 'Lawful Evil',
    diet: 'Ash, oathbreakers, and funeral smoke',
    image: '🗡️',
    cost: 10500,
    specialAbility: petAbility('Hellfire Smite', 'A mounted-warrior strike wrapped in cursed flame.', 5, 2.8, 'hp', 14, 3),
  },
  {
    id: 'tarrasque',
    name: 'Tarrasque',
    description: 'The legendary engine of destruction. Furniture is a temporary condition around it.',
    baseStats: { str: 30, dex: 11, con: 30, int: 3, wis: 11, cha: 11 },
    growth: { str: 2, dex: 0, con: 3, int: 0, wis: 0, cha: 0 },
    alignment: 'Unaligned',
    diet: 'Everything',
    image: '🦖',
    cost: 15000,
    specialAbility: petAbility('Swallow Whole', 'Devours the enemy in a single bite.', 6, 4.0, 'hp', 18, 2),
  },
];

export const SPECIES: Record<string, Species> = Object.fromEntries(speciesList.map((species) => [species.id, species]));

export const HEROES: Encounter[] = [
  {
    id: 'mosquito',
    name: 'Mosquito',
    description: 'A tiny but relentless bloodsucker that somehow insists on heroically ruining your evening.',
    level: 0,
    hp: 8,
    maxHp: 8,
    stats: { str: 6, dex: 14, con: 8, int: 1, wis: 7, cha: 1 },
    reward: 8,
    icon: '🦟',
    tier: 'trivial',
    specialAbility: heroAbility('Needle Rush', 'A shrill dive that lands faster than it should.', 2, 1.1, 3),
  },
  {
    id: 'pet_rat',
    name: 'Pet Rat',
    description: 'A rescued street rat defending its corner with admirable nerve and unpleasant teeth.',
    level: 0,
    hp: 12,
    maxHp: 12,
    stats: { str: 8, dex: 13, con: 9, int: 2, wis: 10, cha: 4 },
    reward: 12,
    icon: '🐀',
    tier: 'trivial',
    specialAbility: heroAbility('Cornered Snap', 'Launches a desperate bite from perfect cover.', 2, 1.2, 2),
  },
  {
    id: 'angry_sheep',
    name: 'Angry Sheep',
    description: 'A fiercely territorial farm guardian with a bell, a glare, and a civic sense of duty.',
    level: 0,
    hp: 18,
    maxHp: 18,
    stats: { str: 10, dex: 10, con: 10, int: 2, wis: 8, cha: 3 },
    reward: 18,
    icon: '🐑',
    tier: 'trivial',
    specialAbility: heroAbility('Ram Charge', 'Drops its head and commits to the entire problem at once.', 2, 1.25, 1),
  },
  {
    id: 'militia_recruit',
    name: 'Militia Recruit',
    description: 'A nervous young spear-carrier in padded leather, trying very hard to look heroic.',
    level: 1,
    hp: 20,
    maxHp: 20,
    stats: { str: 10, dex: 10, con: 11, int: 8, wis: 9, cha: 8 },
    reward: 16,
    icon: '🪖',
    tier: 'low',
    specialAbility: heroAbility('Braced Thrust', 'Plants the rear foot and drives the spear cleanly through guard.', 2, 1.25, 2),
  },
  {
    id: 'hedge_mage',
    name: 'Hedge Mage',
    description: 'A village spellcaster with patched robes, a stubborn jaw, and just enough magic to be dangerous.',
    level: 2,
    hp: 24,
    maxHp: 24,
    stats: { str: 8, dex: 11, con: 10, int: 14, wis: 11, cha: 10 },
    reward: 20,
    icon: '🔮',
    tier: 'low',
    specialAbility: heroAbility('Briar Bolt', 'Snaps out a crude but vicious knot of force and thorns.', 2, 1.35, 3),
  },
  {
    id: 'shrine_cleric',
    name: 'Shrine Cleric',
    description: 'A junior battle-priest armed with a mace, a travel icon, and a firm belief that your pets need correction.',
    level: 3,
    hp: 26,
    maxHp: 26,
    stats: { str: 11, dex: 9, con: 12, int: 10, wis: 13, cha: 11 },
    reward: 24,
    icon: '📿',
    tier: 'low',
    specialAbility: heroAbility('Sanctified Smash', 'A downward mace blow wrapped in blunt divine certainty.', 2, 1.35, 2),
  },
  {
    id: 'town_guard',
    name: 'Town Guard',
    description: 'A disciplined watchman armed with a spear, a shield, and inconveniently decent morals.',
    level: 4,
    hp: 28,
    maxHp: 28,
    stats: { str: 12, dex: 11, con: 12, int: 9, wis: 10, cha: 9 },
    reward: 28,
    icon: '🛡️',
    tier: 'low',
    specialAbility: heroAbility('Shield Press', 'Pins with the shield and drives the spear through the opening.', 2, 1.4, 1),
  },
  {
    id: 'lantern_acolyte',
    name: 'Lantern Acolyte',
    description: 'A temple novice carrying a mace, bright conviction, and enough healing prayers to be annoying.',
    level: 5,
    hp: 36,
    maxHp: 36,
    stats: { str: 11, dex: 10, con: 12, int: 11, wis: 14, cha: 12 },
    reward: 42,
    icon: '🕯️',
    tier: 'standard',
    specialAbility: heroAbility('Lantern Flare', 'A blinding burst followed by a righteous crack across the jaw.', 2, 1.45, 2),
  },
  {
    id: 'ranger_scout',
    name: 'Ranger Scout',
    description: 'A sharp-eyed wilderness tracker who insists your creatures are an ecological concern.',
    level: 6,
    hp: 44,
    maxHp: 44,
    stats: { str: 13, dex: 15, con: 12, int: 11, wis: 13, cha: 10 },
    reward: 56,
    icon: '🏹',
    tier: 'standard',
    specialAbility: heroAbility('Marked Shot', 'Picks a seam in the target and looses before the blink finishes.', 2, 1.5, 4),
  },
  {
    id: 'squire_captain',
    name: 'Squire Captain',
    description: 'A young commander with good posture, polished mail, and more courage than experience.',
    level: 7,
    hp: 54,
    maxHp: 54,
    stats: { str: 15, dex: 12, con: 14, int: 11, wis: 11, cha: 12 },
    reward: 72,
    icon: '⚔️',
    tier: 'standard',
    specialAbility: heroAbility("Commander's Charge", 'Steps through the centerline and hits like it expects applause.', 3, 1.6, 2),
  },
  {
    id: 'apprentice_mage',
    name: 'Apprentice Mage',
    description: 'A bookish prodigy eager to prove that a well-cast spell can solve any monster problem.',
    level: 8,
    hp: 58,
    maxHp: 58,
    stats: { str: 9, dex: 12, con: 12, int: 16, wis: 13, cha: 12 },
    reward: 92,
    icon: '📘',
    tier: 'standard',
    specialAbility: heroAbility('Arcane Lance', 'Shapes a precise bolt of force and sends it straight through the center mass.', 3, 1.65, 4),
  },
  {
    id: 'temple_hound',
    name: 'Temple Hound',
    description: 'A holy war dog bred to sniff out fiends, thieves, and parlours with suspicious basements.',
    level: 9,
    hp: 70,
    maxHp: 70,
    stats: { str: 16, dex: 14, con: 14, int: 4, wis: 13, cha: 8 },
    reward: 114,
    icon: '🐕',
    tier: 'standard',
    specialAbility: heroAbility('Righteous Pounce', 'Launches in low and rips upward with disciplined fury.', 2, 1.6, 3),
  },
  {
    id: 'griffon_rider',
    name: 'Griffon Rider',
    description: 'An aerial lancer from the city watch, all feathers, brass, and lawful momentum.',
    level: 10,
    hp: 82,
    maxHp: 82,
    stats: { str: 17, dex: 15, con: 15, int: 12, wis: 12, cha: 13 },
    reward: 140,
    icon: '🦅',
    tier: 'elite',
    specialAbility: heroAbility('Sky Spear Dive', 'Drops from above with lance, claws, and terrible timing.', 3, 1.8, 3),
  },
  {
    id: 'witch_hunter_captain',
    name: 'Witch Hunter Captain',
    description: 'A grim investigator with silvered bolts, a long coat, and specific feelings about your clientele.',
    level: 10,
    hp: 78,
    maxHp: 78,
    stats: { str: 15, dex: 16, con: 14, int: 13, wis: 14, cha: 12 },
    reward: 146,
    icon: '🕵️',
    tier: 'elite',
    specialAbility: heroAbility('Silver Bolt Volley', 'Lets fly a practiced burst aimed exactly where monsters hate it.', 3, 1.75, 4),
  },
  {
    id: 'druid_warden',
    name: 'Druid Warden',
    description: 'A forest guardian who has decided your enterprise counts as unnatural interference.',
    level: 11,
    hp: 96,
    maxHp: 96,
    stats: { str: 14, dex: 13, con: 16, int: 13, wis: 17, cha: 12 },
    reward: 170,
    icon: '🌿',
    tier: 'elite',
    specialAbility: heroAbility('Thornsnare', 'Calls up hooked roots and whiplash vines in a single violent pulse.', 3, 1.9, 2),
  },
  {
    id: 'alchemical_inquisitor',
    name: 'Alchemical Inquisitor',
    description: 'A sanctioned purifier armed with brass bombs, antiseptic fury, and excellent posture.',
    level: 11,
    hp: 92,
    maxHp: 92,
    stats: { str: 13, dex: 15, con: 15, int: 15, wis: 14, cha: 11 },
    reward: 176,
    icon: '⚗️',
    tier: 'elite',
    specialAbility: heroAbility('Sunfire Bomb', 'Lobs a radiant charge that blooms at exactly the wrong moment for you.', 3, 1.85, 3),
  },
  {
    id: 'paladin_errant',
    name: 'Paladin Errant',
    description: 'A mounted oathsworn crusader with radiant steel and an absolutely exhausting code.',
    level: 12,
    hp: 112,
    maxHp: 112,
    stats: { str: 18, dex: 12, con: 17, int: 12, wis: 14, cha: 16 },
    reward: 204,
    icon: '✨',
    tier: 'elite',
    specialAbility: heroAbility('Radiant Smite', 'Loads the blade with judgment and sends it home.', 3, 2.0, 2),
  },
  {
    id: 'battle_mage_marshal',
    name: 'Battle Mage Marshal',
    description: 'A line officer who teaches that formation fighting and evocation are not separate subjects.',
    level: 12,
    hp: 106,
    maxHp: 106,
    stats: { str: 14, dex: 13, con: 16, int: 17, wis: 13, cha: 13 },
    reward: 210,
    icon: '🪄',
    tier: 'elite',
    specialAbility: heroAbility('Force Halberd', 'Conjures a brutal arc of force and follows through like a drill instructor.', 3, 1.95, 4),
  },
  {
    id: 'pegasus_knight',
    name: 'Pegasus Knight',
    description: 'A skyborne champion sweeping in from the upper winds to put down airborne nuisances.',
    level: 13,
    hp: 128,
    maxHp: 128,
    stats: { str: 18, dex: 16, con: 17, int: 12, wis: 14, cha: 15 },
    reward: 242,
    icon: '🐎',
    tier: 'elite',
    specialAbility: heroAbility('Lancefall', 'A screaming descent that lands lance-first and keeps going.', 3, 2.0, 3),
  },
  {
    id: 'sky_lancer',
    name: 'Sky Lancer',
    description: 'A disciplined aerial duelist who fights like gravity is just a suggestion.',
    level: 13,
    hp: 124,
    maxHp: 124,
    stats: { str: 17, dex: 17, con: 16, int: 12, wis: 13, cha: 14 },
    reward: 248,
    icon: '🪽',
    tier: 'elite',
    specialAbility: heroAbility('Gale Arrowstorm', 'Cuts across the arena and looses a storm of wind-borne shafts.', 3, 1.95, 4),
  },
  {
    id: 'unicorn_guardian',
    name: 'Unicorn Guardian',
    description: 'A radiant woodland sentinel whose mercy unfortunately does not extend to your battle roster.',
    level: 14,
    hp: 146,
    maxHp: 146,
    stats: { str: 19, dex: 16, con: 18, int: 11, wis: 17, cha: 18 },
    reward: 284,
    icon: '🦄',
    tier: 'elite',
    specialAbility: heroAbility('Purity Horn', 'Spears forward in a burst of blinding grace.', 3, 2.05, 3),
  },
  {
    id: 'sacred_lionheart',
    name: 'Sacred Lionheart',
    description: 'A leonine holy champion whose courage arrives several seconds before the rest of it.',
    level: 14,
    hp: 150,
    maxHp: 150,
    stats: { str: 20, dex: 15, con: 18, int: 10, wis: 15, cha: 17 },
    reward: 292,
    icon: '🦁',
    tier: 'elite',
    specialAbility: heroAbility('Solar Maul', 'Brings both paws down in a radiant collapse of momentum.', 3, 2.1, 2),
  },
  {
    id: 'veteran_cleric',
    name: 'Veteran Cleric',
    description: 'A battle-priest with calm eyes, heavy armor, and enough divine power to make this personal.',
    level: 15,
    hp: 166,
    maxHp: 166,
    stats: { str: 17, dex: 11, con: 18, int: 13, wis: 18, cha: 16 },
    reward: 330,
    icon: '⛪',
    tier: 'elite',
    specialAbility: heroAbility('Judgment Hammer', 'Drives a blessed hammer blow through your best intentions.', 3, 2.15, 2),
  },
  {
    id: 'silver_banner_templar',
    name: 'Silver Banner Templar',
    description: 'A parade-perfect crusader who somehow hits as hard as a siege engine.',
    level: 15,
    hp: 170,
    maxHp: 170,
    stats: { str: 18, dex: 12, con: 18, int: 12, wis: 15, cha: 17 },
    reward: 338,
    icon: '🚩',
    tier: 'elite',
    specialAbility: heroAbility('Banner Charge', 'Turns discipline into velocity and velocity into pain.', 3, 2.1, 3),
  },
  {
    id: 'storm_sorcerer',
    name: 'Storm Sorcerer',
    description: 'A smiling duelist wrapped in wind and lightning, treating the arena like a weather experiment.',
    level: 16,
    hp: 188,
    maxHp: 188,
    stats: { str: 12, dex: 16, con: 17, int: 15, wis: 14, cha: 19 },
    reward: 380,
    icon: '⛈️',
    tier: 'elite',
    specialAbility: heroAbility('Thunderstep', 'Vanishes in one crack of thunder and reappears with the blast still attached.', 3, 2.2, 4),
  },
  {
    id: 'bladesinger_duelist',
    name: 'Bladesinger Duelist',
    description: 'An elegant elf swordmage moving so cleanly it feels unfair at several levels.',
    level: 16,
    hp: 182,
    maxHp: 182,
    stats: { str: 15, dex: 19, con: 16, int: 17, wis: 13, cha: 14 },
    reward: 388,
    icon: '🎼',
    tier: 'elite',
    specialAbility: heroAbility('Spellcut Flurry', 'A singing sequence of cuts threaded with razor-fine magic.', 3, 2.15, 5),
  },
  {
    id: 'deva_emissary',
    name: 'Deva Emissary',
    description: 'A celestial envoy sent to restore order, light, and a deeply inconvenient amount of judgment.',
    level: 17,
    hp: 212,
    maxHp: 212,
    stats: { str: 20, dex: 17, con: 18, int: 17, wis: 18, cha: 19 },
    reward: 436,
    icon: '😇',
    tier: 'boss',
    specialAbility: heroAbility('Heavenfall Slash', 'Drops a blazing diagonal cut from high over the battlefield.', 4, 2.25, 4),
  },
  {
    id: 'phoenix_knight',
    name: 'Phoenix Knight',
    description: 'A burnished champion whose armor glows like banked coals just before the fire gets serious.',
    level: 17,
    hp: 206,
    maxHp: 206,
    stats: { str: 19, dex: 16, con: 18, int: 14, wis: 15, cha: 18 },
    reward: 444,
    icon: '🔥',
    tier: 'boss',
    specialAbility: heroAbility('Ashen Rebirth', 'Explodes forward in fire-wreathed momentum that feels impossible to stop.', 4, 2.25, 3),
  },
  {
    id: 'archdruid',
    name: 'Archdruid',
    description: 'An elder shapechanger who regards your stable of monstrosities as a policy failure.',
    level: 18,
    hp: 238,
    maxHp: 238,
    stats: { str: 15, dex: 14, con: 19, int: 16, wis: 20, cha: 17 },
    reward: 496,
    icon: '🍃',
    tier: 'boss',
    specialAbility: heroAbility('Verdant Cataclysm', 'Calls the whole room to life and sends it your way.', 4, 2.3, 3),
  },
  {
    id: 'couatl_oracle',
    name: 'Couatl Oracle',
    description: 'A radiant serpent seer striking with serene certainty and deeply inconvenient prophecy.',
    level: 18,
    hp: 232,
    maxHp: 232,
    stats: { str: 16, dex: 18, con: 18, int: 17, wis: 19, cha: 18 },
    reward: 504,
    icon: '🐍',
    tier: 'boss',
    specialAbility: heroAbility("Oracle's Venom", 'Lands a prophetic strike that feels fated several seconds in advance.', 4, 2.25, 4),
  },
  {
    id: 'planetar_guardian',
    name: 'Planetar Guardian',
    description: 'A towering heavenly enforcer descending with sword drawn and zero tolerance for evil pets.',
    level: 19,
    hp: 266,
    maxHp: 266,
    stats: { str: 23, dex: 18, con: 20, int: 18, wis: 19, cha: 20 },
    reward: 562,
    icon: '🪽',
    tier: 'boss',
    specialAbility: heroAbility('Greatsword of Dawn', 'Brings a sun-bright blade over the top with annihilating force.', 4, 2.35, 4),
  },
  {
    id: 'dragonlance_prince',
    name: 'Dragonlance Prince',
    description: 'A royal dragon-slayer in mirrored steel who has mistaken your parlour for a campaign objective.',
    level: 19,
    hp: 260,
    maxHp: 260,
    stats: { str: 22, dex: 17, con: 20, int: 17, wis: 16, cha: 21 },
    reward: 570,
    icon: '👑',
    tier: 'boss',
    specialAbility: heroAbility('Wyrm-Piercer', 'Plants an enormous lance with all the ceremony of a final sentence.', 4, 2.4, 3),
  },
  {
    id: 'gold_dragon_ally',
    name: 'Gold Dragon Ally',
    description: 'A noble dragon who would prefer diplomacy but has reluctantly agreed that force is faster.',
    level: 20,
    hp: 296,
    maxHp: 296,
    stats: { str: 24, dex: 16, con: 22, int: 18, wis: 19, cha: 21 },
    reward: 634,
    icon: '🐲',
    tier: 'boss',
    specialAbility: heroAbility('Sunfire Breath', 'Exhales a regal furnace of golden flame.', 4, 2.5, 4),
  },
  {
    id: 'archmage_sentinel',
    name: 'Archmage Sentinel',
    description: 'A fortress-minded wizard who treats the arena like one more place to deny access.',
    level: 20,
    hp: 286,
    maxHp: 286,
    stats: { str: 13, dex: 15, con: 20, int: 22, wis: 18, cha: 17 },
    reward: 644,
    icon: '🔷',
    tier: 'boss',
    specialAbility: heroAbility('Meteor Seal', 'Pins the target under a perfectly measured burst of falling force.', 4, 2.45, 5),
  },
  {
    id: 'eladrin_blademaster',
    name: 'Eladrin Blademaster',
    description: 'A fey sword-saint flickering between seasons and striking before thought catches up.',
    level: 21,
    hp: 328,
    maxHp: 328,
    stats: { str: 22, dex: 21, con: 21, int: 18, wis: 17, cha: 20 },
    reward: 712,
    icon: '🌟',
    tier: 'boss',
    specialAbility: heroAbility('Season Splitter', 'A seasonal flash-step and cut that lands in all four quarters of the year at once.', 4, 2.5, 5),
  },
  {
    id: 'astral_monk',
    name: 'Astral Monk',
    description: 'A star-eyed ascetic striking with impossible reach and alarming tranquility.',
    level: 21,
    hp: 320,
    maxHp: 320,
    stats: { str: 20, dex: 22, con: 20, int: 16, wis: 20, cha: 16 },
    reward: 722,
    icon: '🌌',
    tier: 'boss',
    specialAbility: heroAbility('Star Palm', 'An open-handed strike that lands like a falling constellation.', 4, 2.45, 5),
  },
  {
    id: 'solar_champion',
    name: 'Solar Champion',
    description: 'An angelic warlord blazing with enough sanctified force to sterilize the entire arena.',
    level: 22,
    hp: 362,
    maxHp: 362,
    stats: { str: 26, dex: 20, con: 22, int: 20, wis: 20, cha: 22 },
    reward: 798,
    icon: '☀️',
    tier: 'boss',
    specialAbility: heroAbility('Judicator Beam', 'Levels a sun-bright line of condemnation straight through the target.', 4, 2.6, 5),
  },
  {
    id: 'archon_inquisitor',
    name: 'Archon Inquisitor',
    description: 'A severe celestial magistrate who has come prepared to enforce every clause personally.',
    level: 22,
    hp: 354,
    maxHp: 354,
    stats: { str: 24, dex: 19, con: 22, int: 20, wis: 21, cha: 21 },
    reward: 808,
    icon: '⚖️',
    tier: 'boss',
    specialAbility: heroAbility('Celestial Verdict', 'Delivers sentence and impact in the same terrible instant.', 4, 2.55, 4),
  },
  {
    id: 'ancient_treant',
    name: 'Ancient Treant',
    description: 'A walking cathedral of bark and patience, awakened to end what it calls your indoor blight.',
    level: 23,
    hp: 398,
    maxHp: 398,
    stats: { str: 27, dex: 10, con: 25, int: 16, wis: 20, cha: 18 },
    reward: 892,
    icon: '🌳',
    tier: 'boss',
    specialAbility: heroAbility('Rootquake', 'Rips up the ground and slams it forward like a living wall.', 4, 2.6, 2),
  },
  {
    id: 'adamantine_champion',
    name: 'Adamantine Champion',
    description: 'A living bulwark of disciplined steel whose idea of subtlety is only slightly smaller than a siege gate.',
    level: 23,
    hp: 392,
    maxHp: 392,
    stats: { str: 28, dex: 14, con: 24, int: 15, wis: 17, cha: 17 },
    reward: 904,
    icon: '🪙',
    tier: 'boss',
    specialAbility: heroAbility('Worldbreaker Swing', 'Commits to a two-handed arc with architecture-ending intent.', 4, 2.65, 3),
  },
  {
    id: 'kirin_herald',
    name: 'Ki-rin Herald',
    description: 'A heavenly beast bringing omens, thunder, and a complete lack of respect for evil dragons.',
    level: 24,
    hp: 436,
    maxHp: 436,
    stats: { str: 25, dex: 18, con: 24, int: 20, wis: 22, cha: 23 },
    reward: 994,
    icon: '🦌',
    tier: 'boss',
    specialAbility: heroAbility('Storm Hoof', 'Descends like a thunderhead and hits with the weather still attached.', 4, 2.7, 4),
  },
  {
    id: 'mythic_ranger',
    name: 'Mythic Ranger',
    description: 'A legendary huntmaster carrying enough enchanted ammunition to depopulate a nightmare.',
    level: 24,
    hp: 428,
    maxHp: 428,
    stats: { str: 22, dex: 24, con: 22, int: 18, wis: 22, cha: 17 },
    reward: 1006,
    icon: '🎯',
    tier: 'boss',
    specialAbility: heroAbility('Comet Barrage', 'Lets fly a skywriting sequence of impossible shots.', 4, 2.65, 5),
  },
  {
    id: 'bahamuts_chosen',
    name: "Bahamut's Chosen",
    description: 'A legendary draconic champion in radiant armor, carrying the final word on monster management.',
    level: 25,
    hp: 476,
    maxHp: 476,
    stats: { str: 28, dex: 19, con: 25, int: 19, wis: 22, cha: 24 },
    reward: 1104,
    icon: '👑',
    tier: 'boss',
    specialAbility: heroAbility('Platinum Judgment', 'Brings down a draconic sentence in radiant steel and holy fire.', 5, 2.8, 4),
  },
  {
    id: 'sainted_archon',
    name: 'Sainted Archon',
    description: 'A halo-crowned crusader whose mercy arrives only after the battlefield stops moving.',
    level: 25,
    hp: 468,
    maxHp: 468,
    stats: { str: 27, dex: 20, con: 24, int: 20, wis: 22, cha: 24 },
    reward: 1118,
    icon: '👼',
    tier: 'boss',
    specialAbility: heroAbility('Crownfire Edict', 'Declares the result and then makes the arena agree.', 5, 2.75, 5),
  },
  {
    id: 'tiamat',
    name: 'Tiamat the Dragon Queen',
    description: 'Five-headed catastrophe, tyrant of dragons, and the only opponent here who is evil on purpose.',
    level: 26,
    hp: 540,
    maxHp: 540,
    stats: { str: 30, dex: 18, con: 28, int: 22, wis: 21, cha: 26 },
    reward: 1400,
    icon: '🐉',
    tier: 'boss',
    specialAbility: heroAbility('Fivefold Breath', 'Unleashes a layered storm of acid, frost, fire, lightning, and venom.', 5, 3.0, 4),
  },
  {
    id: 'empyrean_exemplar',
    name: 'Empyrean Exemplar',
    description: 'A divine colossus carrying a storm-wreathed glaive and the confidence of an inevitable ending.',
    level: 26,
    hp: 528,
    maxHp: 528,
    stats: { str: 30, dex: 19, con: 27, int: 20, wis: 22, cha: 24 },
    reward: 1420,
    icon: '⛈️',
    tier: 'boss',
    specialAbility: heroAbility('World-Ending Glaive', 'Turns the whole arc of a polearm into a thunderclap.', 5, 2.9, 4),
  },
];

export const ENCOUNTERS = HEROES;

export const ITEMS: Record<string, Item> = {
  monster_chow: {
    id: 'monster_chow',
    name: 'Monster Chow',
    description: 'Restores 30 Hunger.',
    cost: 10,
    type: 'food',
    value: 30,
    icon: '🍖',
  },
  minor_potion: {
    id: 'minor_potion',
    name: 'Minor Potion of Healing',
    description: 'Restores 20 HP.',
    cost: 20,
    type: 'heal',
    value: 20,
    icon: '🧪',
  },
  major_potion: {
    id: 'major_potion',
    name: 'Major Potion of Healing',
    description: 'Restores 50 HP.',
    cost: 50,
    type: 'heal',
    value: 50,
    icon: '⚗️',
  },
  pet_brush: {
    id: 'pet_brush',
    name: 'Enchanted Brush',
    description: 'Restores 20 Happiness.',
    cost: 15,
    type: 'social',
    value: 20,
    icon: '🪮',
  },
  haste_potion: {
    id: 'haste_potion',
    name: 'Potion of Haste',
    description: 'Battle: Your pet attacks twice for the next 3 turns.',
    cost: 40,
    type: 'buff',
    value: 3,
    icon: '⚡',
  },
};
